respawnx:
- 0
respawny:
- 0
respawnz:
- 0
respawnyaw:
- 0
respawnpitch:
- 0
respawnworld:
- world
targetworld:
- world
spawnx:
- 0
spawny:
- 0
spawnz:
- 0
spawnyaw:
- 0
spawnpitch:
- 0
movetargetworld:
- world
respawnhealth: 20
respawnfood: 0
respawnmessage: null
system: true
joinsystem: true
movesystem: true
cpenalty: false
dpenalty: false
exceptionworldlist:
exceptionplayerlist: