spawnx:
- 0
spawny:
- 0
spawnz:
- 0
spawnyaw:
- 0
spawnpitch:
- 0
spawnworld:
- world
targetworld:
- world
respawnhealth: 20
respawnfood: 0
respawnmessage: null
system: true
joinsystem: true
exceptionworldlist:
exceptionplayerlist: